### ISSUE TITLE
Docker build doesn't work 

### ISSUE THREAD

**Issue by tirohia** [hartwigmedical/gridss-purple-linx#1]
The end goal is to build a singularity image that can be run on our local HPC. There are a number of issues with the Dockerfile preventing an initial build using Docker. 

The docker file builds from gridss/gridss:2.5.2. I have my own build for this, which I created from the Dockerfile from the [Papenfuss lab](https://github.com/PapenfussLab/gridss/tree/master/docker), changing all references to gridss-2.5.0 to gridss-2.5.2 and adding a line to install sambamba (it will build without this, but won't run). This build works on it's own. 
My preference would have been to use a build from dockerhub, but the latest version of gridss that I can find on there is version 2.4

Attempting to build from gridss/gridss:2.5.2, the line 
```
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y circos pkg-config libgd-dev
```
results in errors along the lines of :
```
The following packages have unmet dependencies:
 perl : Depends: perl-base (= 5.22.1-9ubuntu0.6) but 5.26.1-6ubuntu0.3 is to be installed
 perl-base : Breaks: perl (< 5.26.1~) but 5.22.1-9ubuntu0.6 is to be installed
E: Unable to correct problems, you have held broken packages.
The command '/bin/sh -c apt-get install -y perl-base netbase rename perl' returned a non-zero code: 100
```
I suspect that this is due to something missing from the gridss/gridss:2.5.2 build, as if you swap out 
```
FROM gridss/gridss:2.5.2
```
for 
```
FROM ubuntu:18.04
```
then it works. That or, I suspect, when apt-get is looking for repositories, it's looking for repositories for gridss/gridss:2.5.2 rather than unbuntu, of which there are none, because if I start trying to install perl dependencies, it eventually starts telling me that packages are not found. 

The second issue that I've come across with this Dockerfile is with the following section:
```
COPY external/hmftools/amber/target/amber-${AMBER_VERSION}-jar-with-dependencies.jar /opt/hmftools
COPY external/hmftools/count-bam-lines/target/count-bam-lines-${COBALT_VERSION}-jar-with-dependencies.jar /opt/hmftools
COPY external/hmftools/purity-ploidy-estimator/target/purity-ploidy-estimator-${PURPLE_VERSION}-jar-with-dependencies.jar /opt/hmftools
COPY external/hmftools/sv-linx/target/sv-linx-${LINX_VERSION}-jar-with-dependencies.jar /opt/hmftools
COPY gridss-purple-linx.sh /opt/gridss-purple-linx/
```
There might be on the computer where this dockerfile was created, but there is nothing in external/hmftools/amber/target/ to be copied to the docker. I've managed to find jar files for amber, cobalt and purple, though they are not called amber-${AMBER_VERSION}-jar-with-dependencies.jar, rather, just amber-${AMBER_VERSION}.jar - same general theme for cobalt and purple. Copying those across gets past those steps (no idea whether that's going to break things when I get this running, I haven't got that far yet). 
There is, however, no jar file that I can find for sv-linx. There is a release [here](https://github.com/hartwigmedical/hmftools/releases/tag/sv-linx-v1-3), but no jar file. 

I'm currently attempting to cobble together a Dockerfile from the gridss and the grids-purple-linx Dockerfiles, as not being able to build from the gridss/gridss:2.5.2 build, will result in this build being built without gridss, which I'm guessing will break things. This should be do-able, but I'm not sure how to get around the lack of sv-linx.jar

**Comment by d-cameron** [comment]
> it's looking for repositories for gridss/gridss:2.5.2 rather than unbuntu, of which there are none

The image isn't on dockerhub because I'm still working on it. It's mostly done but the gridss-purple-linx.sh scripts doesn't yet include linx.

This is also why the readme is completely empty.

Give me a week or so and we should have a working, documented image ready.

**Comment by tirohia** [comment]
I think I'd be able to get it working if it the linx jar file was in there somewhere. I've got the gridss one that's by itself working - though I did have to add sambamba via getting a static version and copying it into the Dockerfile. 

Not to worry, happy to wait for a week, looking forward to it. I'd use the pipeline V5 version but that appears to be tied up into google cloud.

**Comment by d-cameron** [comment]
I'm just waiting on a colleague to update linx to remove the final hartwig
database dependency from linx. Should have the images all done by early
next week.

**Comment by d-cameron** [comment]
Refactor is now complete. The driver script can now be run from outside docker if you have the appropriate dependencies installed.
