### ISSUE TITLE
Check at least minimum required memory is available at start

### ISSUE THREAD

**Issue by mjko1210** [hartwigmedical/gridss-purple-linx#12]
Hi,

I'm testing this tool using example data (CPCT12345678R.bam, CPCT12345678T.bam) with docker approach. 

I got this error:
"/usr/bin/time -a -o $timinglogfile java -Xmx$jvmheap $jvm_args -Dgridss.gridss.output_to_temp_file=true -cp $gridss_jar gridss.AssembleBreakends TMP_DIR=$workingdir WORKING_DIR=$workingdir REFERENCE_SEQUENCE=$reference WORKER_THREADS=$threads O=$assembly $input_args $blacklist_arg $config_args" command completed with exit code 1.

My command was : 
docker run --ulimit nofile=100000:100000 \
        -v /Users/mko/Downloads/hg19:/refdata \
        -v /Users/mko/Downloads/gridss-purple-linx/smoke_test:/data/ \
        gridss/gridss-purple-linx:1.0.0 \
        -n /data/CPCT12345678R.bam \
        -t /data/CPCT12345678T.bam \
        -v /data/smoketest.vcf \
        -s smoketest \
        --normal_sample CPCT12345678R \
        --tumour_sample CPCT12345678T \
        --snvvcf /data/CPCT12345678T.somatic_caller_post_processed.vcf.gz \
        --jvmheap 15g \
        -- validation_stringency LENIENT 

I have bwa installed and all the reference index files were generated.

According to error message from log file, I was trying to run bwa command separately (bwa mem -L 0,0 -t 8 /Users/mko/Downloads/hg19/refgenomes/Homo_sapiens.GRCh37.GATK.illumina/Homo_sapiens.GRCh37.GATK.illumina.fasta /Users/mko/Downloads/gridss-purple-linx/smoke_test/gridss/CPCT12345678R.bam.gridss.working/CPCT12345678R.bam.realign.0.fq)

However, I got 
[E::main_mem] fail to open file `/Users/mko/Downloads/gridss-purple-linx/smoke_test/gridss/CPCT12345678R.bam.gridss.working/CPCT12345678R.bam.realign.0.fq'.
I can't find this file. 

I've attached log file.
[gridss.full.20200204_000600.0bc638180a5d.286.log](https://github.com/hartwigmedical/gridss-purple-linx/files/4150821/gridss.full.20200204_000600.0bc638180a5d.286.log)

Thanks in advance,
MJ

**Comment by d-cameron** [comment]
>Exception in thread "main" java.lang.RuntimeException: Subprocess terminated with with exit status 137. Failed executing "bwa mem -L 0,0 -t 8 /refdata/refgenomes/Homo_sapiens.GRCh37.GATK.illumina/Homo_sapiens.GRCh37.GATK.illumina.fasta 

Exit status 137 indicates out of memory. I have managed to reproduce this error locally by reducing the memory available to the docker container. The smoke test will run with a bit over 8GB of memory, but on real data, GRIDSS requires at least 16GB and has been optimised to run on a 8 core machine with 25-32GB of available memory.

**Comment by d-cameron** [comment]
This evaded the existing memory check because `java -Xms100g -version` crashes as expected except when run from within a docker container in which case an OOM error is not raised.

**Comment by mjko1210** [comment]
Thank you for your comments. This time I was able to run the command and gridss log file looks fine (no error). However, I don't see any output files from "purple" folder so as "amber".
Does the command I pasted above suppose to generate all outcomes? Thanks again!

**Comment by mjko1210** [comment]
Sorry. I just changed gridss/gridss-purple-linx:1.0.0 to gridss/gridss-purple-linx:latest. It shows all the files in each folder now.
