### ISSUE TITLE
Unregconized tag types

### ISSUE THREAD

**Issue by jdekanter** [hartwigmedical/gridss-purple-linx#15]
First of all, thank you for writing these extremely useful methods!
In our lab, we use the gridss-purple-linx pipeline for the detection of SV in all our tumor samples (together with a matched normal). We make use of a high-performance computing facility and run the pipeline with the hg38 reference genome.

I have run ~20 samples without a problem, but lately some samples fail.
The error messages are always the same. First I get two of the following errors (in the gridss.full log):

> INFO    2020-07-30 13:11:07     AssemblyEvidenceSource  Completed assembly on chunk 147 (8:77095235-8:87095234) in 67s (1.120 min)
> INFO    2020-07-30 13:11:07     SAMFileUtil     Sorting ./gridss/14806DX2MSC.assembly.bam.gridss.working/gridss.tmp.14806DX2MSC.assembly.bam.assembly.chunk147.bam
> INFO    2020-07-30 13:11:07     AssemblyEvidenceSource  Starting assembly on chunk 153 (8:137095235-9:1706598)
> WARNING 2020-07-30 13:11:10     AssemblyAttributes      Sanity check failure: asm73-30916 has mapq below minimum
> ERROR   2020-07-30 13:11:10     NonReferenceContigAssembler     Sanity check failure: found path with no support (4:49656732)
> WARNING 2020-07-30 13:11:11     PositionalAssembler     Error during assembly of chromosome 4 (10342 reads in graph). Attempting recovery by rebuilding assembly graph.
> java.lang.RuntimeException: Sanity check failure: found path with no support (4:49656732)
>         at au.edu.wehi.idsv.debruijn.positional.NonReferenceContigAssembler.callContig(NonReferenceContigAssembler.java:616)
>         at au.edu.wehi.idsv.debruijn.positional.NonReferenceContigAssembler.flushCallsOutsideRetainWindow(NonReferenceContigAssembler.java:208)
>         at au.edu.wehi.idsv.debruijn.positional.NonReferenceContigAssembler.ensureCalledContig(NonReferenceContigAssembler.java:238)
>         at au.edu.wehi.idsv.debruijn.positional.NonReferenceContigAssembler.hasNext(NonReferenceContigAssembler.java:172)
>         at au.edu.wehi.idsv.debruijn.positional.PositionalAssembler.flushIfRequired(PositionalAssembler.java:83)
>         at au.edu.wehi.idsv.debruijn.positional.PositionalAssembler.ensureAssembler(PositionalAssembler.java:240)
>         at au.edu.wehi.idsv.debruijn.positional.PositionalAssembler.ensureAssembler(PositionalAssembler.java:110)
>         at au.edu.wehi.idsv.debruijn.positional.PositionalAssembler.hasNext(PositionalAssembler.java:68)
>         at au.edu.wehi.idsv.AssemblyEvidenceSource.assembleChunk(AssemblyEvidenceSource.java:240)
>         at au.edu.wehi.idsv.AssemblyEvidenceSource.assembleChunk(AssemblyEvidenceSource.java:198)
>         at au.edu.wehi.idsv.AssemblyEvidenceSource.lambda$assembleBreakends$2(AssemblyEvidenceSource.java:100)
>         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
>         at java.lang.Thread.run(Thread.java:748)

And

> ERROR   2020-07-30 14:04:37     NonReferenceContigAssembler     Sanity check failure: found path with no support (MT:16158)
> WARNING 2020-07-30 14:04:37     PositionalAssembler     Error during assembly of chromosome MT (0 reads in graph). Attempting recovery by rebuilding assembly graph.
> java.lang.RuntimeException: Sanity check failure: found path with no support (MT:16158)
>         at au.edu.wehi.idsv.debruijn.positional.NonReferenceContigAssembler.callContig(NonReferenceContigAssembler.java:616)
>         at au.edu.wehi.idsv.debruijn.positional.NonReferenceContigAssembler.flushCallsOutsideRetainWindow(NonReferenceContigAssembler.java:208)
>         at au.edu.wehi.idsv.debruijn.positional.NonReferenceContigAssembler.ensureCalledContig(NonReferenceContigAssembler.java:238)
>         at au.edu.wehi.idsv.debruijn.positional.NonReferenceContigAssembler.hasNext(NonReferenceContigAssembler.java:172)
>         at au.edu.wehi.idsv.debruijn.positional.PositionalAssembler.flushIfRequired(PositionalAssembler.java:83)
>         at au.edu.wehi.idsv.debruijn.positional.PositionalAssembler.ensureAssembler(PositionalAssembler.java:240)
>         at au.edu.wehi.idsv.debruijn.positional.PositionalAssembler.ensureAssembler(PositionalAssembler.java:110)
>         at au.edu.wehi.idsv.debruijn.positional.PositionalAssembler.hasNext(PositionalAssembler.java:68)
>         at au.edu.wehi.idsv.AssemblyEvidenceSource.assembleChunk(AssemblyEvidenceSource.java:240)
>         at au.edu.wehi.idsv.AssemblyEvidenceSource.assembleChunk(AssemblyEvidenceSource.java:198)
>         at au.edu.wehi.idsv.AssemblyEvidenceSource.lambda$assembleBreakends$2(AssemblyEvidenceSource.java:100)
>         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
>         at java.lang.Thread.run(Thread.java:748)

Later, during Variant calling, I get errors, saying there is an unrecognized tag types:

> [Thu Jul 30 14:34:12 CEST 2020] gridss.IdentifyVariants done. Elapsed time: 6.55 minutes.
> Runtime.totalMemory()=11273764864
> Exception in thread "main" java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.lang.RuntimeException: htsjdk.samtools.SAMFormatException: Unrecognized tag type: ^A
>         at au.edu.wehi.idsv.VariantCaller.runTasks(VariantCaller.java:86)
>         at au.edu.wehi.idsv.VariantCaller.callBreakends(VariantCaller.java:56)
>         at gridss.IdentifyVariants.doWork(IdentifyVariants.java:32)
>         at gridss.cmdline.MultipleSamFileCommandLineProgram.doWork(MultipleSamFileCommandLineProgram.java:190)
>         at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:295)
>         at gridss.IdentifyVariants.main(IdentifyVariants.java:26)
> Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.lang.RuntimeException: htsjdk.samtools.SAMFormatException: Unrecognized tag type: ^A
>         at java.util.concurrent.FutureTask.report(FutureTask.java:122)
>         at java.util.concurrent.FutureTask.get(FutureTask.java:192)
>         at au.edu.wehi.idsv.VariantCaller.runTasks(VariantCaller.java:77)
>         ... 5 more
> Caused by: java.lang.RuntimeException: java.lang.RuntimeException: htsjdk.samtools.SAMFormatException: Unrecognized tag type: ^A
>         at au.edu.wehi.idsv.VariantCallIterator.ensureNext(VariantCallIterator.java:195)
>         at au.edu.wehi.idsv.VariantCallIterator.hasNext(VariantCallIterator.java:206)
>         at au.edu.wehi.idsv.util.AsyncBufferedIterator$ReaderRunnable.run(AsyncBufferedIterator.java:165)
>         at java.lang.Thread.run(Thread.java:748)
> Caused by: java.lang.RuntimeException: htsjdk.samtools.SAMFormatException: Unrecognized tag type: ^A
>         at au.edu.wehi.idsv.util.DuplicatingIterable$DuplicatingIterableIterator.ensureNext(DuplicatingIterable.java:122)
>         at au.edu.wehi.idsv.util.DuplicatingIterable$DuplicatingIterableIterator.hasNext(DuplicatingIterable.java:127)
>         at au.edu.wehi.idsv.MaximalEvidenceCliqueIterator$EvidenceToGraphNodeIterator.computeNext(MaximalEvidenceCliqueIterator.java:63)
>         at au.edu.wehi.idsv.MaximalEvidenceCliqueIterator$EvidenceToGraphNodeIterator.computeNext(MaximalEvidenceCliqueIterator.java:56)
>         at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:145)
>         at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:140)
>         at com.google.common.collect.Iterators$PeekingImpl.hasNext(Iterators.java:1182)
>         at au.edu.wehi.idsv.util.WindowedSortingIterator.advanceUnderlying(WindowedSortingIterator.java:71)
>         at au.edu.wehi.idsv.util.WindowedSortingIterator.computeNext(WindowedSortingIterator.java:57)
>         at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:145)
>         at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:140)
>         at com.google.common.collect.Iterators$PeekingImpl.hasNext(Iterators.java:1182)
>         at au.edu.wehi.idsv.graph.RectangleGraphNodeMergingIterator.computeNext(RectangleGraphNodeMergingIterator.java:26)
>         at au.edu.wehi.idsv.graph.RectangleGraphNodeMergingIterator.computeNext(RectangleGraphNodeMergingIterator.java:15)
>         at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:145)
>         at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:140)
>         at au.edu.wehi.idsv.graph.RectangleGraphMaximalCliqueIterator.computeNext(RectangleGraphMaximalCliqueIterator.java:25)
>         at au.edu.wehi.idsv.graph.RectangleGraphMaximalCliqueIterator.computeNext(RectangleGraphMaximalCliqueIterator.java:16)
>         at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:145)
>         at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:140)
>         at au.edu.wehi.idsv.MaximalEvidenceCliqueIterator.computeNext(MaximalEvidenceCliqueIterator.java:151)
>         at au.edu.wehi.idsv.MaximalEvidenceCliqueIterator.computeNext(MaximalEvidenceCliqueIterator.java:23)
>         at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:145)
>         at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:140)
>         at com.google.common.collect.Iterators$5.computeNext(Iterators.java:662)
>         at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:145)
>         at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:140)
>         at au.edu.wehi.idsv.VariantCallIterator$AsyncDirectionalIterator.run(VariantCallIterator.java:127)
>         at au.edu.wehi.idsv.VariantCallIterator$AsyncDirectionalIterator.lambda$new$0(VariantCallIterator.java:108)
>         ... 1 more
> Caused by: htsjdk.samtools.SAMFormatException: Unrecognized tag type: ^A
>         at htsjdk.samtools.BinaryTagCodec.readSingleValue(BinaryTagCodec.java:351)
>         at htsjdk.samtools.BinaryTagCodec.readTags(BinaryTagCodec.java:282)
>         at htsjdk.samtools.BAMRecord.decodeAttributes(BAMRecord.java:415)
>         at htsjdk.samtools.BAMRecord.getAttribute(BAMRecord.java:394)
>         at htsjdk.samtools.SAMRecord.isValid(SAMRecord.java:2066)
>         at htsjdk.samtools.BAMFileReader$BAMFileIterator.decode(BAMFileReader.java:867)
>         at htsjdk.samtools.BAMFileReader$BAMFileIterator.access$1900(BAMFileReader.java:777)
>         at htsjdk.samtools.BAMFileReader$BAMFileIterator$AsyncBamDecoder.transform(BAMFileReader.java:916)
>         at htsjdk.samtools.BAMFileReader$BAMFileIterator$AsyncBamDecoder.transform(BAMFileReader.java:899)
>         at htsjdk.samtools.util.AsyncReadTaskRunner.processNextBatch(AsyncReadTaskRunner.java:228)
>         at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:616)
>         at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:591)
>         at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
>         ... 1 more
> [Thu Jul 30 14:34:12 CEST 2020] gridss.IdentifyVariants done. Elapsed time: 6.55 minutes.
> Runtime.totalMemory()=11273764864
> Exception in thread "main" java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.lang.RuntimeException: htsjdk.samtools.SAMFormatException: Unrecognized tag type: ^A
>         at au.edu.wehi.idsv.VariantCaller.runTasks(VariantCaller.java:86)
>         at au.edu.wehi.idsv.VariantCaller.callBreakends(VariantCaller.java:56)
>         at gridss.IdentifyVariants.doWork(IdentifyVariants.java:32)
>         at gridss.cmdline.MultipleSamFileCommandLineProgram.doWork(MultipleSamFileCommandLineProgram.java:190)
>         at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:295)
>         at gridss.IdentifyVariants.main(IdentifyVariants.java:26)
> Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.lang.RuntimeException: htsjdk.samtools.SAMFormatException: Unrecognized tag type: ^A
>         at java.util.concurrent.FutureTask.report(FutureTask.java:122)
>         at java.util.concurrent.FutureTask.get(FutureTask.java:192)
>         at au.edu.wehi.idsv.VariantCaller.runTasks(VariantCaller.java:77)
>         ... 5 more
> Caused by: java.lang.RuntimeException: java.lang.RuntimeException: htsjdk.samtools.SAMFormatException: Unrecognized tag type: ^A
>         at au.edu.wehi.idsv.VariantCallIterator.ensureNext(VariantCallIterator.java:195)
>         at au.edu.wehi.idsv.VariantCallIterator.hasNext(VariantCallIterator.java:206)
>         at au.edu.wehi.idsv.util.AsyncBufferedIterator$ReaderRunnable.run(AsyncBufferedIterator.java:165)
>         at java.lang.Thread.run(Thread.java:748)
> Caused by: java.lang.RuntimeException: htsjdk.samtools.SAMFormatException: Unrecognized tag type: ^A
>         at au.edu.wehi.idsv.util.DuplicatingIterable$DuplicatingIterableIterator.ensureNext(DuplicatingIterable.java:122)
>         at au.edu.wehi.idsv.util.DuplicatingIterable$DuplicatingIterableIterator.hasNext(DuplicatingIterable.java:127)
>         at au.edu.wehi.idsv.MaximalEvidenceCliqueIterator$EvidenceToGraphNodeIterator.computeNext(MaximalEvidenceCliqueIterator.java:63)
>         at au.edu.wehi.idsv.MaximalEvidenceCliqueIterator$EvidenceToGraphNodeIterator.computeNext(MaximalEvidenceCliqueIterator.java:56)
>         at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:145)
>         at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:140)
>         at com.google.common.collect.Iterators$PeekingImpl.hasNext(Iterators.java:1182)
>         at au.edu.wehi.idsv.util.WindowedSortingIterator.advanceUnderlying(WindowedSortingIterator.java:71)
>         at au.edu.wehi.idsv.util.WindowedSortingIterator.computeNext(WindowedSortingIterator.java:57)
>         at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:145)
>         at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:140)
>         at com.google.common.collect.Iterators$PeekingImpl.hasNext(Iterators.java:1182)
>         at au.edu.wehi.idsv.graph.RectangleGraphNodeMergingIterator.computeNext(RectangleGraphNodeMergingIterator.java:26)
>         at au.edu.wehi.idsv.graph.RectangleGraphNodeMergingIterator.computeNext(RectangleGraphNodeMergingIterator.java:15)
>         at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:145)
>         at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:140)
>         at au.edu.wehi.idsv.graph.RectangleGraphMaximalCliqueIterator.computeNext(RectangleGraphMaximalCliqueIterator.java:25)
>         at au.edu.wehi.idsv.graph.RectangleGraphMaximalCliqueIterator.computeNext(RectangleGraphMaximalCliqueIterator.java:16)
>         at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:145)
>         at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:140)
>         at au.edu.wehi.idsv.MaximalEvidenceCliqueIterator.computeNext(MaximalEvidenceCliqueIterator.java:151)
>         at au.edu.wehi.idsv.MaximalEvidenceCliqueIterator.computeNext(MaximalEvidenceCliqueIterator.java:23)
>         at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:145)
>         at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:140)
>         at com.google.common.collect.Iterators$5.computeNext(Iterators.java:662)
>         at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:145)
>         at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:140)
>         at au.edu.wehi.idsv.VariantCallIterator$AsyncDirectionalIterator.run(VariantCallIterator.java:127)
>         at au.edu.wehi.idsv.VariantCallIterator$AsyncDirectionalIterator.lambda$new$0(VariantCallIterator.java:108)
>         ... 1 more
> Caused by: htsjdk.samtools.SAMFormatException: Unrecognized tag type: ^A
>         at htsjdk.samtools.BinaryTagCodec.readSingleValue(BinaryTagCodec.java:351)
>         at htsjdk.samtools.BinaryTagCodec.readTags(BinaryTagCodec.java:282)
>         at htsjdk.samtools.BAMRecord.decodeAttributes(BAMRecord.java:415)
>         at htsjdk.samtools.BAMRecord.getAttribute(BAMRecord.java:394)
>         at htsjdk.samtools.SAMRecord.isValid(SAMRecord.java:2066)
>         at htsjdk.samtools.BAMFileReader$BAMFileIterator.decode(BAMFileReader.java:867)
>         at htsjdk.samtools.BAMFileReader$BAMFileIterator.access$1900(BAMFileReader.java:777)
>         at htsjdk.samtools.BAMFileReader$BAMFileIterator$AsyncBamDecoder.transform(BAMFileReader.java:916)
>         at htsjdk.samtools.BAMFileReader$BAMFileIterator$AsyncBamDecoder.transform(BAMFileReader.java:899)
>         at htsjdk.samtools.util.AsyncReadTaskRunner.processNextBatch(AsyncReadTaskRunner.java:228)
>         at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:616)
>         at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:591)
>         at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
>         ... 1 more

The original BAM files seem fine, and none of or other pipelines fail with these samples. 
I asked a colleague to run the pipeline for me, 
and when he started it with the exact same script, the pipeline finished without any errors.

As I was the only one in our group who encountered this error, 
I checked whether it had something to do with my bashrc, or bash_profile, but even after literally copying both from my colleague as a test, the problems kept occurring. 
This probably has something to do with my user settings within our system, but I can't figure out what is different between me and my colleague. I was wondering whether you might have any idea what I should be looking for.

**Comment by d-cameron** [comment]
> Sanity check failure: found path with no support

This issue was fixed in GRIDSS 2.9.1. The workaround for this problem is to run the latest version of the standalone GRIDSS docker image, writing the VCF to the location expected by gridss-purple-linx, then running the gridss-purple-linx docker. It will detect that GRIDSS VCF has already been generated and just run the downstream steps.

Note that we haven't updated the gridss-purple-linx image to the latest version since there are upstream dependency changes (PURPLE now uses Sage for SNV calling), as well as signficant implementation optimisations to our overall pipeline. We will be releasing a new docker image when the Hartwig [pipeline v5](https://github.com/hartwigmedical/pipeline5) project has stabilised.

> htsjdk.samtools.SAMFormatException: Unrecognized tag type: ^A

We haven't encountered this error before ourselves. Are you encountering it only on the samples that have a warning/error during the assembly stage? This issue seems like a corruption of one of the intermediate files used by GRIDSS. Deleting *.gridss.working and rerunning should fix this issue.

**Comment by jdekanter** [comment]
Thank you for your answer!
I have rerun one of the samples that gave this error, but didn't think to delete the working directories. Trying that now first.
If that does not work, I will try the updated GRIDSS standalone, and see if that solves that problem for me.

Also the samples that do finish encounter the error during assembly, so I wouldn't expect that that causes the "unrecognized tag type" errors.

I will let you know if one of these has solved my problem!

**Comment by d-cameron** [comment]
> Also the samples that do finish encounter the error during assembly, so I wouldn't expect that that causes the "unrecognized tag type" errors.

The assembly process has automatic recovery logic in it so most errors were already recoverable. v2.9.1 fixed the root cause of the last (known) assembly crash.

**Comment by jdekanter** [comment]
Rerunning the sample after deleting the working directories did not work.
My last try was requesting to be deleted from an old group in linux that I am not part of anymore. After this, gridss-purple-linx ran without a problem. Apparently, it had something to do with dependencies, or paths that I inherited from being part of that group. 
Thanks for your time, and sorry I can't give a clear answer as to what exactly caused this.
