### ISSUE TITLE
Variant Calling in non-model organisms

### ISSUE THREAD

**Issue by janawold1** [hartwigmedical/gridss-purple-linx#16]
Hello,
I am attempting to generate a population level de novo call set of structural variants in a non-model organism. I've tested a number of different pipelines and really like the gridss-purple-linx pipeline. Any chance there's plans to make this work for non-human species in the near future? Or are there some tweaks to the pipeline that can be made to work with different species?

Many thanks,

Jana

**Comment by p-priestley** [comment]
Hi Jana.    GRIDSS will likely work well for this use case.

PURPLE and LINX, however, are designed solely for the purpose of somatic analysis of human tumor samples.   There are many implicit and explicit assumptions that relate to both the human genome specifically and cancer.   They would not be suitable for your use case.

**Comment by janawold1** [comment]
Many thanks! Do you have some suggestions on the easiest way to convert/interpret GRIDSS breakend notation into structural variant calls?

**Comment by d-cameron** [comment]
What notation do you want to convert/interpret the GRIDSS breakend notation into? Fundamentally, GRIDSS detects breakpoints:^ it states that this DNA segments is connected to this other DNA segment. Delly, manta, pindel, breakdancer, etc are also breakpoint detection programs. GRIDSS uses `BND` notation as this makes this explicit.

Historically, there has not been any separation between variant detection and variant interpretation as this distinction is not required for SNVs. This is not the case for SVs. Detection and interpretation are distinct steps and the gridss/purple/linx pipeline treats them as such: GRIDSS detects SVs, PURPLE detects CNVs, and LINX does the interpretation and classification. For example, we only call a deletion when there is a breakpoint connecting the start<->end of the deleted segment AND there is a copy number loss in the 'deleted region'. If there's no CN loss then the event isn't actually a deletion (even though other SV callers will report this as a `<DEL>`). See https://github.com/hartwigmedical/hmftools/blob/master/sv-linx/README.md#overview-of-event-classification-system-in-linx for an overview of what it is that LINX does - rearrangement event interpretation is not at all straight-forward when one has to consider complex events. Unfortunately, LINX is specialised for human somatic rearrangements and there's almost no other tools that actually do genomic rearrangement classification. 

If you're looking at germline samples then most of the complexities present in cancer genomes don't exist and you don't have to deal with complex rearrangements such as chromothripsis, or ubiquitous aneuploidy. In such cases, you might be able to get away with just assuming the simplest explaination. GRIDSS has a helper utility.

For my bespoke rearrangement analysis, I use the `StructuralVariantAnnotation` BioConductor package. This converts the calls from most SV callers (gridss, manta, delly, lumpy, svaba, pindel, breakdancer, ...) into a standard breakpoint-based notation, and I use the standard BioConductor object for the downstream analysis (gene overlap detection, breakmarking against truth sets, etc). This format can be exported to BEDPE if you prefer that notation.

GRIDSS has a helper script in the /examples/ directory if you just want a simple DEL/DUP/INS/INV annotation.

^ Or in the case of single breakends, this DNA segment is connected to another DNA segment but we can't unambigously place it.
