### ISSUE TITLE
No amber, purple results from CPCT_test example Oct 20,2020

### ISSUE THREAD

**Issue by TnakaNY** [hartwigmedical/gridss-purple-linx#19]
I downloaded CPCT12345678T/R.bam, vcf file and ran the gridss-purple-linx pipeline with docker.
GRIDSS seemed to run successfully, but no results in amber and purple folder. Logs folder is also empty. Linx folder was not generated.

Used command is here:
docker run --ulimit nofile=100000:100000 -v D:/GRIDSStest/refdata:/refdata -v D:/GRIDSStest/test3:/data/ gridss/gridss-purple-linx:latest -n /data/CPCT12345678R.bam -t /data/CPCT12345678T.bam -v /data/smoketest.vcf -s smoketest --snvvcf /data/CPCT12345678T.somatic_caller_post_processed.vcf.gz --jvmheap 15g --threads 8 --validation_stringency LENIENT

Consoleoutput and gridss full log are attached.
[Console.txt](https://github.com/hartwigmedical/gridss-purple-linx/files/5409972/Console.txt)
[gridss.full.20201020_150927.7e5e05ffd115.308.log](https://github.com/hartwigmedical/gridss-purple-linx/files/5409974/gridss.full.20201020_150927.7e5e05ffd115.308.log)

How do I run this pipeline, corectly? Any suggestions?

**Comment by alexiswl** [comment]
I would refer to this comment on another issue regarding the expectations of the test data: https://github.com/hartwigmedical/gridss-purple-linx/issues/17#issuecomment-713277479
