### ISSUE TITLE
ability to pass validation_stringency parameter to Docker image

### ISSUE THREAD

**Issue by srinipr4** [hartwigmedical/gridss-purple-linx#21]
--validation_stringency is a parameter in gridss-purple-linx.sh - but it doesn't seem possible to provide it as a parameter to the docker file. It would be great if that can be addressed or if the default can be changed to "LENIENT".

**Comment by alexiswl** [comment]
Could you provide an example of how you are invoking the docker container? 

The entrypoint to the docker container is `/opt/gridss-purple-linx/gridss-purple-linx.sh`. All trailing parameters are added as arguments to the shell script.

**Comment by srinipr4** [comment]
So, I have actually converted the docker image to a singularity image since we do not have docker in our compute cluster. This is how I run the scg image : 
singularity run -B <bam_repo> -B gridss-purple-linx/refdata/gpl_ref_data_hg37 \
-B <output-dir> gridds-purple-linx.img \
--normal_bam <normal bam> --tumour_bam <tumour bam> \
--sample <samplename> --output_dir <output-dir> \
--ref_genome_version HG37 --nosnvvcf --ref_dir gridss-purple-linx/refdata/gpl_ref_data_hg37 

when I pass --validation_stringency LENIENT along with the command I get the following error:
/opt/gridss-purple-linx/gridss-purple-linx.sh: unrecognized option '--validation_stringency'
without that, my command works but fails downstream because of some problematic reads in the bam.

**Comment by srinipr4** [comment]
the validation_stringency parameter is not being set in `LONGOPTS` and not populated in the next section (parser logic) in /opt/gridss-purple-linx/gridss-purple-linx.sh
Thanks!

**Comment by alexiswl** [comment]
Yep nice catch! Looks like at `validation_stringency` is set to `STRICT` by default and not redefined in the args loop at https://github.com/hartwigmedical/gridss-purple-linx/blob/1a23bb3b2e7d636265ff757aa0557cbc6f262ec7/gridss-purple-linx.sh#L79

**Comment by srinipr4** [comment]
Great, thanks for looking into this. Would it be possible to implement this fix on your end sometime soon? 
Thank you!

**Comment by alexiswl** [comment]
I don't maintain this repo.

I'd recommend forking this repo, adding in the fix into your fork. You can use the fork for the time being. Then generate a pull request from the fork to this repo for the patch to be added in.

**Comment by charlesshale** [comment]
validation_stringency can now be set as in input parameter

**Comment by srinipr4** [comment]
Oh great - thank you!

**Comment by srinipr4** [comment]
Hi, could you also please push the updated docker image to docker hub?

**Comment by srinipr4** [comment]
@charlesshale - I am having trouble rebuilding the docker image in our environment. It would be very helpful if you could push the updated image to docker hub. Thanks again!

**Comment by srinipr4** [comment]
Hi, I also noticed that the validation stringency parameter was not being passed to gridss.sh, which was failing at some point due to the same issue. I've added a patch with a fix for it. Thanks!

**Comment by d-cameron** [comment]
#24
