### ISSUE TITLE
Documentation: Sage not used

### ISSUE THREAD

**Issue by alexiswl** [hartwigmedical/gridss-purple-linx#25]
Is SAGE called by subprocess in this pipeline? 

It is noted in the [v1.3.2 release](https://github.com/hartwigmedical/gridss-purple-linx/releases/tag/v1.3.2), the SAGE JAR is set to v2.4 yet there is no mention of the SageApplication java jar being called at any stage. Is it called by a subprocess? Or has it been accidentally omitted?

**Comment by charlesshale** [comment]
Sage is not called in this pipeline, that's correct. A somatic VCF can optionally be provided in the call to Purple to improve the somatic fit, and this would typically be produced by Sage or Strelka.
