### ISSUE TITLE
GRIPSS is set to run in "tumor-only mode"

### ISSUE THREAD

**Issue by toddajohnson** [hartwigmedical/gridss-purple-linx#28]
The other programs in the standalone GRIDSS-PURPLE-LINX script are all passed arguments for paired tumor-normal samples as necessary, but the arguments passed to GRIPSS do not include the "-reference" argument, so it runs only in tumor-only mode (Log output: "Running in tumor-only mode")
The java call for gripss includes gripss_args at the end, but gripss_arg is not set like the corresponding points AMBER and COBALT code blocks.  I modified my local copy of the gripss-purple-linx.sh script to include following above the call to java in the gripss block and it is now running with reference and tumor:

	if [[ $tumour_only != true ]] ; then
		gripss_args="-reference $normal_sample"
	else
		gripss_args=""
	fi

**Comment by alexiswl** [comment]
Great spot! I've omitted the `else` as this would override any inputs that the user sets through the `--gripss_args` option.
