### ISSUE TITLE
Reference name for '703' not found in sequence dictionary

### ISSUE THREAD

**Issue by YingYa** [hartwigmedical/gridss-purple-linx#31]
Hi,

I am runing gridss-purple-linx.v1.3.2.simg with singularity but failed on the step 'gridss.PreprocessForBreakendAssembly':
Exception in thread "main" java.lang.IllegalArgumentException: Reference name for '703' not found in sequence dictionary.

my bam files were alined to Homo_sapiens_assembly38.fasta, downloaded from GATKbundle (ftp.broadinstitute.org/gsapubftp-anonymous/bundle/hg38). The reference contains 3366 cpntigs.

Should I realigned the data to GCA_000001405.15_GRCh38_no_alt_analysis_set.fna, the reference in gpl_ref_data_38, that I could run the gridss-purple-linx pipelines?

Thanks,
Ya

**Comment by d-cameron** [comment]
The reference genome must match the reference gnome provided in the reference data package.
See https://github.com/hartwigmedical/gridss-purple-linx#reference-data

The 38 reference genome is located at refgenomes/Homo_sapiens.GRCh38/Homo_sapiens_assembly38.fasta

It looks like you're probably using the correct reference genome. Are you using the reference data package?

**Comment by YingYa** [comment]
Yes, I download the reference data from: https://resources.hartwigmedicalfoundation.nl/ then navigate to HMFTools-Resources/GRIDSS-Purple-Linx-Docker/gpl_ref_data_hg38.gz
1) https://nextcloud.hartwigmedicalfoundation.nl/s/LTiKTd8XxBqwaiC/download?path=%2FHMFTools-Resources%2FGRIDSS-Purple-Linx-Docker&files=gpl_ref_data_38.gz
2) The hg38 reference genome located is 'gpl_ref_data_38/refgenomes/Homo_sapiens.GRCh38/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna', not 'refgenomes/Homo_sapiens.GRCh38/Homo_sapiens_assembly38.fasta'.

**Comment by charlesshale** [comment]
The correct ref genome for 38 is the no-alt one, that is:

gpl_ref_data_38/refgenomes/Homo_sapiens.GRCh38/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna'

**Comment by YingYa** [comment]
I think there may be three ways for me to run the gridss-purple-linx pipelines with my aligned BAM files:
1) BWA: realign to GCA_000001405.15_GRCh38_no_alt_analysis_set.fna using BWA
2) Picard ReorderSam: reorders reads in a BAM file to match the contig ordering in GCA_000001405.15_GRCh38_no_alt_analysis_set.fna, as determined by exact name matching of contigs. Reads mapped to contigs absent in the new reference are unmapped.
3) use Homo_sapiens_assembly38.fasta instead of GCA_000001405.15_GRCh38_no_alt_analysis_set.fna, and then rebuild the index.

Which way maybe not working for gridss-purple-linx pipelines?

**Comment by p-priestley** [comment]
Closing issue due to age.  I hope you worked out these issues.   If outstanding still, please open a new issue
