### ISSUE TITLE
Issue when using Strelka somatic VCF

### ISSUE THREAD

**Issue by tea-kostic** [hartwigmedical/gridss-purple-linx#34]
Hi!

I am running Gridss/Purple/Linx pipeline(cwl version) with somatic VCF file from Strelka that was preprocessed using the steps explained [here](https://github.com/hartwigmedical/hmftools/tree/master/purple#preparing-strelka-output-for-purple). 

This is what the VCF file looks like:

#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	HCC1143BL	HCC1143
chr1	182686	.	A	G	.	QSS_ref	AC=0;AF=0.00;AN=0;NT=het;QSS=4;QSS_NT=4;SGT=AG->AG;SOMATIC;TQSS=1;TQSS_NT=1;set=FilteredInAll	AD:AU:CU:DP:FDP:GU:SDP:SUBDP:TU	20,16:20,66:1,1:37:0:16,28:0:0:0,0	34,1:34,94:0,0:35:0:1,1:0:0:0,0

This is the error that I get:

Exception in thread "main" java.lang.NullPointerException
at com.hartwig.hmftools.common.variant.AllelicDepth.containsAllelicDepth(AllelicDepth.java:20)
at com.hartwig.hmftools.common.variant.SomaticVariantFactory.createVariant(SomaticVariantFactory.java:126)
at com.hartwig.hmftools.common.variant.SomaticVariantFactory.createVariant(SomaticVariantFactory.java:118)
at com.hartwig.hmftools.purple.PurityPloidyEstimateApplication.lambda$somaticVariants$0(PurityPloidyEstimateApplication.java:391)
at com.hartwig.hmftools.common.variant.enrich.VariantHotspotEnrichment.accept(VariantHotspotEnrichment.java:38)
at com.hartwig.hmftools.purple.PurityPloidyEstimateApplication.somaticVariants(PurityPloidyEstimateApplication.java:399)
at com.hartwig.hmftools.purple.PurityPloidyEstimateApplication.<init>(PurityPloidyEstimateApplication.java:149)
at com.hartwig.hmftools.purple.PurityPloidyEstimateApplication.main(PurityPloidyEstimateApplication.java:103)

What is this error suggesting and how can it be resolved?

Thanks,
Tea

**Comment by p-priestley** [comment]
I believe PURPLE will ignore the specific variant since it is filtered.   

Could you check please that all variants in the vcf have an AD field?

**Comment by tea-kostic** [comment]
These are the steps followed to produce the VCF file:

**STEP 1 - merge strelka snp and indel output:**
---------------------------------------------
java -jar /opt/GenomeAnalysisTK.jar --analysis_type CombineVariants --out strelka.merged.vcf --genotypemergeoption unsorted --reference_sequence ../GCA_000001405.15_GRCh38_no_alt_analysis_set.fasta --variant ../strelka_all.somatic.snvs.vcf --variant ../strelka_all.somatic.indels.vcf
---------------------------------------------
**STEP 2 - replace NORMAL and TUMOR with actual sample names**
---------------------------------------------
sed -i -e 's/NORMAL/HCC1143BL/g'    -e 's/TUMOR/HCC1143/g'  strelka.merged.vcf
---------------------------------------------
**STEP 3 - add allelic depth(AD) field**
---------------------------------------------
java -Xmx4G -cp /opt/purple-2.51.jar com.hartwig.hmftools.purple.tools.AnnotateStrelkaWithAllelicDepth -in strelka.merged.vcf -out strelka.merged.annotated.vcf.gz

[Here](https://drive.google.com/file/d/1nFJodoC8g58GbxOslHZD5ksnf13Gl7fZ/view?usp=sharing) is a zip file containing VCFs produced after each step, which might help you identify the underlying issue.

Thanks!

**Comment by p-priestley** [comment]
The AD field is mandatory, so every record int the vcf must have an AD.   However there are some records in step3.vcf.gz that don't

zgrep -v '#' step3.vcf.gz | grep -v AD | head -10

I think the AD annotation has likely failed due to the ALT being written as "." for these records. eg.

chr1	789696	.	G	.	.	QSS_ref	AN=0;NT=conflict;QSS=2;QSS_NT=0;SGT=GG->GG;SOMATIC;TQSS=1;TQSS_NT=1;set=FilteredInAll	AU:CU:DP:FDP:GU:SDP:SUBDP:TU	1,13:2,14:75:6:62,319:0:0:4,38	6,36:4,27:125:18:96,550:0:0:1,42

Not sure why Strelka has not annotated an ALT for these records as we don't use Strelka any more.   None of these records PASS, so perhaps you can filter them?

**Comment by tea-kostic** [comment]
I filtered the VCF file to remove all variants for which AD wasn't present, and rerun the analysis, however PURPLE fails again with the same error as before. Here is the filtered VCF file passed to PURPLE: [strelka.merged.annotated.vcf.gz](https://github.com/hartwigmedical/gridss-purple-linx/files/6453034/strelka.merged.annotated.vcf.gz)

**Comment by p-priestley** [comment]
Tea - we have tried to run with this latest vcf file and PURPLE works fine for us.

**Comment by tea-kostic** [comment]
Hi @p-priestley ,

We figured out what the problem was, it is working now. Thanks for your help!

Best regards,
Tea
