### ISSUE TITLE
Exception in thread "main" java.lang.NullPointerException

### ISSUE THREAD

**Issue by msubirana** [hartwigmedical/gridss-purple-linx#37]
Running the module, I got the following error:

```
11:45:51 - Loading structural variants from /data/VCF/gridss/gripss/NET1T.gripss.somatic.filtered.vcf.gz
11:45:52 - Loading somatic variants from /data/VCF/strelka2/NET1/results/variants/prove/strelka.merged.annotated.vcf.gz
Exception in thread "main" java.lang.NullPointerException
at com.hartwig.hmftools.common.variant.AllelicDepth.containsAllelicDepth(AllelicDepth.java:20)
at com.hartwig.hmftools.common.variant.SomaticVariantFactory.createVariant(SomaticVariantFactory.java:126)
at com.hartwig.hmftools.common.variant.SomaticVariantFactory.createVariant(SomaticVariantFactory.java:118)
at com.hartwig.hmftools.purple.PurityPloidyEstimateApplication.lambda$somaticVariants$0(PurityPloidyEstimateApplication.java:391)
at com.hartwig.hmftools.common.variant.enrich.VariantHotspotEnrichment.accept(VariantHotspotEnrichment.java:38)
at com.hartwig.hmftools.purple.PurityPloidyEstimateApplication.somaticVariants(PurityPloidyEstimateApplication.java:399)
at com.hartwig.hmftools.purple.PurityPloidyEstimateApplication.<init>(PurityPloidyEstimateApplication.java:149)
at com.hartwig.hmftools.purple.PurityPloidyEstimateApplication.main(PurityPloidyEstimateApplication.java:103)
```

It is related with the vcf generated by Strelka2 and the error comes from PURPLE. I generated the vcf using Strelka2 and corrected as the documentation of PURPLE explains (https://github.com/hartwigmedical/hmftools/tree/master/purple)

Any ideas of what is happening?

**Comment by p-priestley** [comment]
Could this be the same problem as here?

https://github.com/hartwigmedical/hmftools/issues/149

**Comment by charlesshale** [comment]
Yes the same issue and is now handled without crashing with this beta release:

https://github.com/hartwigmedical/hmftools/releases/tag/purple-v3.2_beta

If you can attach a snippet your VCF then I can confirm what data is missing / expected.

thanks

**Comment by msubirana** [comment]
`##fileformat=VCFv4.2
##FILTER=<ID=PASS,Description="All filters passed">
##Depth_chr10=35.00
##Depth_chr11=35.00
##Depth_chr12=35.00
##Depth_chr13=35.00
##Depth_chr14=35.00
##Depth_chr15=34.00
##Depth_chr16=35.00
##Depth_chr17=33.00
##Depth_chr18=35.00
##Depth_chr19=34.00
##Depth_chr1=34.00
##Depth_chr20=35.00
##Depth_chr21=34.00
##Depth_chr22=35.00
##Depth_chr2=35.00
##Depth_chr3=35.00
##Depth_chr4=35.00
##Depth_chr5=35.00
##Depth_chr6=35.00
##Depth_chr7=35.00
##Depth_chr8=35.00
##Depth_chr9=34.00
##Depth_chrM=2366.00
##Depth_chrX=34.00
##Depth_chrY=3.00
##FILTER=<ID=HighDepth,Description="Locus depth is greater than 3x the mean chromosome depth in the normal sample">
##FILTER=<ID=LowDepth,Description="Tumor or normal sample read depth at this locus is below 2">
##FILTER=<ID=LowEVS,Description="Somatic Empirical Variant Score (SomaticEVS) is below threshold">
##FORMAT=<ID=AD,Number=R,Type=Integer,Description="Allelic depths for the ref and alt alleles in the order listed">
##FORMAT=<ID=AU,Number=2,Type=Integer,Description="Number of 'A' alleles used in tiers 1,2">
##FORMAT=<ID=BCN50,Number=1,Type=Float,Description="Fraction of filtered reads within 50 bases of the indel.">
##FORMAT=<ID=CU,Number=2,Type=Integer,Description="Number of 'C' alleles used in tiers 1,2">
##FORMAT=<ID=DP,Number=1,Type=Integer,Description="Read depth for tier1 (used+filtered)">
##FORMAT=<ID=DP2,Number=1,Type=Integer,Description="Read depth for tier2">
##FORMAT=<ID=DP50,Number=1,Type=Float,Description="Average tier1 read depth within 50 bases">
##FORMAT=<ID=FDP,Number=1,Type=Integer,Description="Number of basecalls filtered from original read depth for tier1">
##FORMAT=<ID=FDP50,Number=1,Type=Float,Description="Average tier1 number of basecalls filtered from original read depth within 50 bases">
##FORMAT=<ID=GU,Number=2,Type=Integer,Description="Number of 'G' alleles used in tiers 1,2">
##FORMAT=<ID=SDP,Number=1,Type=Integer,Description="Number of reads with deletions spanning this site at tier1">
##FORMAT=<ID=SUBDP,Number=1,Type=Integer,Description="Number of reads below tier1 mapping quality threshold aligned across this site">
##FORMAT=<ID=SUBDP50,Number=1,Type=Float,Description="Average number of reads below tier1 mapping quality threshold aligned across sites within 50 bases">
##FORMAT=<ID=TAR,Number=2,Type=Integer,Description="Reads strongly supporting alternate allele for tiers 1,2">
##FORMAT=<ID=TIR,Number=2,Type=Integer,Description="Reads strongly supporting indel allele for tiers 1,2">
##FORMAT=<ID=TOR,Number=2,Type=Integer,Description="Other reads (weak support or insufficient indel breakpoint overlap) for tiers 1,2">
##FORMAT=<ID=TU,Number=2,Type=Integer,Description="Number of 'T' alleles used in tiers 1,2">
##GATKCommandLine.CombineVariants=<ID=CombineVariants,Version=3.7-0-gcfedb67,Date="Mon Sep 20 16:31:48 CEST 2021",Epoch=1632148308001,CommandLineOptions="analysis_type=CombineVariants input_file=[] showFullBamList=false read_buffer_size=null read_filter=[] disable_read_filter=[] intervals=null excludeIntervals=null interval_set_rule=UNION interval_merging=ALL interval_padding=0 reference_sequence=/gpfs42/robbyfs/scratch/lab_lpasquali/msubirana/ref/GCA_000001405.15_GRCh38_no_alt_analysis_set.fa nonDeterministicRandomSeed=false disableDithering=false maxRuntime=-1 maxRuntimeUnits=MINUTES downsampling_type=BY_SAMPLE downsample_to_fraction=null downsample_to_coverage=1000 baq=OFF baqGapOpenPenalty=40.0 refactor_NDN_cigar_string=false fix_misencoded_quality_scores=false allow_potentially_misencoded_quality_scores=false useOriginalQualities=false defaultBaseQualities=-1 performanceLog=null BQSR=null quantize_quals=0 static_quantized_quals=null round_down_quantized=false disable_indel_quals=false emit_original_quals=false preserve_qscores_less_than=6 globalQScorePrior=-1.0 secondsBetweenProgressUpdates=10 validation_strictness=SILENT remove_program_records=false keep_program_records=false sample_rename_mapping_file=null unsafe=null disable_auto_index_creation_and_locking_when_reading_rods=false no_cmdline_in_header=false sites_only=false never_trim_vcf_format_field=false bcf=false bam_compression=null simplifyBAM=false disable_bam_indexing=false generate_md5=false num_threads=1 num_cpu_threads_per_data_thread=1 num_io_threads=0 monitorThreadEfficiency=false num_bam_file_handles=null read_group_black_list=null pedigree=[] pedigreeString=[] pedigreeValidationType=STRICT allow_intervals_with_unindexed_bam=false generateShadowBCF=false variant_index_type=DYNAMIC_SEEK variant_index_parameter=-1 reference_window_stop=0 phone_home= gatk_key=null tag=NA logging_level=INFO log_to_file=null help=false version=false variant=[(RodBindingCollection [(RodBinding name=variant source=somatic.snvs.vcf.gz)]), (RodBindingCollection [(RodBinding name=variant2 source=somatic.indels.vcf.gz)])] out=/gpfs42/robbyfs/scratch/lab_lpasquali/msubirana/marc/insulinomas/data/WGS/VCF/strelka2/NET1/results/variants/prove/strelka.merged.vcf genotypemergeoption=UNSORTED filteredrecordsmergetype=KEEP_IF_ANY_UNFILTERED multipleallelesmergetype=BY_TYPE rod_priority_list=null printComplexMerges=false filteredAreUncalled=false minimalVCF=false excludeNonVariants=false setKey=set assumeIdenticalSamples=false minimumN=1 suppressCommandLineHeader=false mergeInfoWithMaxAC=false filter_reads_with_N_cigar=false filter_mismatching_base_and_quals=false filter_bases_not_stored=false">
##INFO=<ID=AC,Number=A,Type=Integer,Description="Allele count in genotypes, for each ALT allele, in the same order as listed">
##INFO=<ID=AF,Number=A,Type=Float,Description="Allele Frequency, for each ALT allele, in the same order as listed">
##INFO=<ID=AN,Number=1,Type=Integer,Description="Total number of alleles in called genotypes">
##INFO=<ID=DP,Number=1,Type=Integer,Description="Combined depth across samples">
##INFO=<ID=IC,Number=1,Type=Integer,Description="Number of times RU repeats in the indel allele">
##INFO=<ID=IHP,Number=1,Type=Integer,Description="Largest reference interrupted homopolymer length intersecting with the indel">
##INFO=<ID=MQ,Number=1,Type=Float,Description="RMS Mapping Quality">
##INFO=<ID=MQ0,Number=1,Type=Integer,Description="Total Mapping Quality Zero Reads">
##INFO=<ID=NT,Number=1,Type=String,Description="Genotype of the normal in all data tiers, as used to classify somatic variants. One of {ref,het,hom,conflict}.">
##INFO=<ID=OVERLAP,Number=0,Type=Flag,Description="Somatic indel possibly overlaps a second indel.">
##INFO=<ID=PNOISE,Number=1,Type=Float,Description="Fraction of panel containing non-reference noise at this site">
##INFO=<ID=PNOISE2,Number=1,Type=Float,Description="Fraction of panel containing more than one non-reference noise obs at this site">
##INFO=<ID=QSI,Number=1,Type=Integer,Description="Quality score for any somatic variant, ie. for the ALT haplotype to be present at a significantly different frequency in the tumor and normal">
##INFO=<ID=QSI_NT,Number=1,Type=Integer,Description="Quality score reflecting the joint probability of a somatic variant and NT">
##INFO=<ID=QSS,Number=1,Type=Integer,Description="Quality score for any somatic snv, ie. for the ALT allele to be present at a significantly different frequency in the tumor and normal">
##INFO=<ID=QSS_NT,Number=1,Type=Integer,Description="Quality score reflecting the joint probability of a somatic variant and NT">
##INFO=<ID=RC,Number=1,Type=Integer,Description="Number of times RU repeats in the reference allele">
##INFO=<ID=RU,Number=1,Type=String,Description="Smallest repeating sequence unit in inserted or deleted sequence">
##INFO=<ID=ReadPosRankSum,Number=1,Type=Float,Description="Z-score from Wilcoxon rank sum test of Alt Vs. Ref read-position in the tumor">
##INFO=<ID=SGT,Number=1,Type=String,Description="Most likely somatic genotype excluding normal noise states">
##INFO=<ID=SNVSB,Number=1,Type=Float,Description="Somatic SNV site strand bias">
##INFO=<ID=SOMATIC,Number=0,Type=Flag,Description="Somatic mutation">
##INFO=<ID=SomaticEVS,Number=1,Type=Float,Description="Somatic Empirical Variant Score (EVS) expressing the phred-scaled probability of the call being a false positive observation.">
##INFO=<ID=TQSI,Number=1,Type=Integer,Description="Data tier used to compute QSI">
##INFO=<ID=TQSI_NT,Number=1,Type=Integer,Description="Data tier used to compute QSI_NT">
##INFO=<ID=TQSS,Number=1,Type=Integer,Description="Data tier used to compute QSS">
##INFO=<ID=TQSS_NT,Number=1,Type=Integer,Description="Data tier used to compute QSS_NT">
##INFO=<ID=set,Number=1,Type=String,Description="Source VCF for the merged record in CombineVariants">
##cmdline=/aplic/noarch/software/Strelka/2.9.10.centos6_x86_64/bin/configureStrelkaSomaticWorkflow.py --normalBam /gpfs42/robbyfs/scratch/lab_lpasquali/msubirana/marc/insulinomas/data/WGS/BAM/toSomaticCalling/NET1_BL.bam --tumorBam /gpfs42/robbyfs/scratch/lab_lpasquali/msubirana/marc/insulinomas/data/WGS/BAM/toSomaticCalling/NET1_TI.bam --referenceFasta /gpfs42/robbyfs/scratch/lab_lpasquali/msubirana/ref/GCA_000001405.15_GRCh38_no_alt_analysis_set.fa --runDir /gpfs42/robbyfs/scratch/lab_lpasquali/msubirana/marc/insulinomas/data/WGS/VCF/strelka2/NET1 --indelCandidates /gpfs42/robbyfs/scratch/lab_lpasquali/msubirana/marc/insulinomas/data/WGS/VCF/manta/NET1/results/variants/candidateSmallIndels.vcf.gz --callRegions /gpfs42/robbyfs/scratch/lab_lpasquali/msubirana/ref/callRegions.bed.gz
##content=strelka somatic snv calls
##contig=<ID=chr1,length=248956422>
##contig=<ID=chr2,length=242193529>
##contig=<ID=chr3,length=198295559>
##contig=<ID=chr4,length=190214555>
##contig=<ID=chr5,length=181538259>
##contig=<ID=chr6,length=170805979>
##contig=<ID=chr7,length=159345973>
##contig=<ID=chr8,length=145138636>
##contig=<ID=chr9,length=138394717>
##contig=<ID=chr10,length=133797422>
##contig=<ID=chr11,length=135086622>
##contig=<ID=chr12,length=133275309>
##contig=<ID=chr13,length=114364328>
##contig=<ID=chr14,length=107043718>
##contig=<ID=chr15,length=101991189>
##contig=<ID=chr16,length=90338345>
##contig=<ID=chr17,length=83257441>
##contig=<ID=chr18,length=80373285>
##contig=<ID=chr19,length=58617616>
##contig=<ID=chr20,length=64444167>
##contig=<ID=chr21,length=46709983>
##contig=<ID=chr22,length=50818468>
##contig=<ID=chrX,length=156040895>
##contig=<ID=chrY,length=57227415>
##contig=<ID=chrM,length=16569>
##contig=<ID=chr1_KI270706v1_random,length=175055>
##contig=<ID=chr1_KI270707v1_random,length=32032>
##contig=<ID=chr1_KI270708v1_random,length=127682>
##contig=<ID=chr1_KI270709v1_random,length=66860>
##contig=<ID=chr1_KI270710v1_random,length=40176>
##contig=<ID=chr1_KI270711v1_random,length=42210>
##contig=<ID=chr1_KI270712v1_random,length=176043>
##contig=<ID=chr1_KI270713v1_random,length=40745>
##contig=<ID=chr1_KI270714v1_random,length=41717>
##contig=<ID=chr2_KI270715v1_random,length=161471>
##contig=<ID=chr2_KI270716v1_random,length=153799>
##contig=<ID=chr3_GL000221v1_random,length=155397>
##contig=<ID=chr4_GL000008v2_random,length=209709>
##contig=<ID=chr5_GL000208v1_random,length=92689>
##contig=<ID=chr9_KI270717v1_random,length=40062>
##contig=<ID=chr9_KI270718v1_random,length=38054>
##contig=<ID=chr9_KI270719v1_random,length=176845>
##contig=<ID=chr9_KI270720v1_random,length=39050>
##contig=<ID=chr11_KI270721v1_random,length=100316>
##contig=<ID=chr14_GL000009v2_random,length=201709>
##contig=<ID=chr14_GL000225v1_random,length=211173>
##contig=<ID=chr14_KI270722v1_random,length=194050>
##contig=<ID=chr14_GL000194v1_random,length=191469>
##contig=<ID=chr14_KI270723v1_random,length=38115>
##contig=<ID=chr14_KI270724v1_random,length=39555>
##contig=<ID=chr14_KI270725v1_random,length=172810>
##contig=<ID=chr14_KI270726v1_random,length=43739>
##contig=<ID=chr15_KI270727v1_random,length=448248>
##contig=<ID=chr16_KI270728v1_random,length=1872759>
##contig=<ID=chr17_GL000205v2_random,length=185591>
##contig=<ID=chr17_KI270729v1_random,length=280839>
##contig=<ID=chr17_KI270730v1_random,length=112551>
##contig=<ID=chr22_KI270731v1_random,length=150754>
##contig=<ID=chr22_KI270732v1_random,length=41543>
##contig=<ID=chr22_KI270733v1_random,length=179772>
##contig=<ID=chr22_KI270734v1_random,length=165050>
##contig=<ID=chr22_KI270735v1_random,length=42811>
##contig=<ID=chr22_KI270736v1_random,length=181920>
##contig=<ID=chr22_KI270737v1_random,length=103838>
##contig=<ID=chr22_KI270738v1_random,length=99375>
##contig=<ID=chr22_KI270739v1_random,length=73985>
##contig=<ID=chrY_KI270740v1_random,length=37240>
##contig=<ID=chrUn_KI270302v1,length=2274>
##contig=<ID=chrUn_KI270304v1,length=2165>
##contig=<ID=chrUn_KI270303v1,length=1942>
##contig=<ID=chrUn_KI270305v1,length=1472>
##contig=<ID=chrUn_KI270322v1,length=21476>
##contig=<ID=chrUn_KI270320v1,length=4416>
##contig=<ID=chrUn_KI270310v1,length=1201>
##contig=<ID=chrUn_KI270316v1,length=1444>
##contig=<ID=chrUn_KI270315v1,length=2276>
##contig=<ID=chrUn_KI270312v1,length=998>
##contig=<ID=chrUn_KI270311v1,length=12399>
##contig=<ID=chrUn_KI270317v1,length=37690>
##contig=<ID=chrUn_KI270412v1,length=1179>
##contig=<ID=chrUn_KI270411v1,length=2646>
##contig=<ID=chrUn_KI270414v1,length=2489>
##contig=<ID=chrUn_KI270419v1,length=1029>
##contig=<ID=chrUn_KI270418v1,length=2145>
##contig=<ID=chrUn_KI270420v1,length=2321>
##contig=<ID=chrUn_KI270424v1,length=2140>
##contig=<ID=chrUn_KI270417v1,length=2043>
##contig=<ID=chrUn_KI270422v1,length=1445>
##contig=<ID=chrUn_KI270423v1,length=981>
##contig=<ID=chrUn_KI270425v1,length=1884>
##contig=<ID=chrUn_KI270429v1,length=1361>
##contig=<ID=chrUn_KI270442v1,length=392061>
##contig=<ID=chrUn_KI270466v1,length=1233>
##contig=<ID=chrUn_KI270465v1,length=1774>
##contig=<ID=chrUn_KI270467v1,length=3920>
##contig=<ID=chrUn_KI270435v1,length=92983>
##contig=<ID=chrUn_KI270438v1,length=112505>
##contig=<ID=chrUn_KI270468v1,length=4055>
##contig=<ID=chrUn_KI270510v1,length=2415>
##contig=<ID=chrUn_KI270509v1,length=2318>
##contig=<ID=chrUn_KI270518v1,length=2186>
##contig=<ID=chrUn_KI270508v1,length=1951>
##contig=<ID=chrUn_KI270516v1,length=1300>
##contig=<ID=chrUn_KI270512v1,length=22689>
##contig=<ID=chrUn_KI270519v1,length=138126>
##contig=<ID=chrUn_KI270522v1,length=5674>
##contig=<ID=chrUn_KI270511v1,length=8127>
##contig=<ID=chrUn_KI270515v1,length=6361>
##contig=<ID=chrUn_KI270507v1,length=5353>
##contig=<ID=chrUn_KI270517v1,length=3253>
##contig=<ID=chrUn_KI270529v1,length=1899>
##contig=<ID=chrUn_KI270528v1,length=2983>
##contig=<ID=chrUn_KI270530v1,length=2168>
##contig=<ID=chrUn_KI270539v1,length=993>
##contig=<ID=chrUn_KI270538v1,length=91309>
##contig=<ID=chrUn_KI270544v1,length=1202>
##contig=<ID=chrUn_KI270548v1,length=1599>
##contig=<ID=chrUn_KI270583v1,length=1400>
##contig=<ID=chrUn_KI270587v1,length=2969>
##contig=<ID=chrUn_KI270580v1,length=1553>
##contig=<ID=chrUn_KI270581v1,length=7046>
##contig=<ID=chrUn_KI270579v1,length=31033>
##contig=<ID=chrUn_KI270589v1,length=44474>
##contig=<ID=chrUn_KI270590v1,length=4685>
##contig=<ID=chrUn_KI270584v1,length=4513>
##contig=<ID=chrUn_KI270582v1,length=6504>
##contig=<ID=chrUn_KI270588v1,length=6158>
##contig=<ID=chrUn_KI270593v1,length=3041>
##contig=<ID=chrUn_KI270591v1,length=5796>
##contig=<ID=chrUn_KI270330v1,length=1652>
##contig=<ID=chrUn_KI270329v1,length=1040>
##contig=<ID=chrUn_KI270334v1,length=1368>
##contig=<ID=chrUn_KI270333v1,length=2699>
##contig=<ID=chrUn_KI270335v1,length=1048>
##contig=<ID=chrUn_KI270338v1,length=1428>
##contig=<ID=chrUn_KI270340v1,length=1428>
##contig=<ID=chrUn_KI270336v1,length=1026>
##contig=<ID=chrUn_KI270337v1,length=1121>
##contig=<ID=chrUn_KI270363v1,length=1803>
##contig=<ID=chrUn_KI270364v1,length=2855>
##contig=<ID=chrUn_KI270362v1,length=3530>
##contig=<ID=chrUn_KI270366v1,length=8320>
##contig=<ID=chrUn_KI270378v1,length=1048>
##contig=<ID=chrUn_KI270379v1,length=1045>
##contig=<ID=chrUn_KI270389v1,length=1298>
##contig=<ID=chrUn_KI270390v1,length=2387>
##contig=<ID=chrUn_KI270387v1,length=1537>
##contig=<ID=chrUn_KI270395v1,length=1143>
##contig=<ID=chrUn_KI270396v1,length=1880>
##contig=<ID=chrUn_KI270388v1,length=1216>
##contig=<ID=chrUn_KI270394v1,length=970>
##contig=<ID=chrUn_KI270386v1,length=1788>
##contig=<ID=chrUn_KI270391v1,length=1484>
##contig=<ID=chrUn_KI270383v1,length=1750>
##contig=<ID=chrUn_KI270393v1,length=1308>
##contig=<ID=chrUn_KI270384v1,length=1658>
##contig=<ID=chrUn_KI270392v1,length=971>
##contig=<ID=chrUn_KI270381v1,length=1930>
##contig=<ID=chrUn_KI270385v1,length=990>
##contig=<ID=chrUn_KI270382v1,length=4215>
##contig=<ID=chrUn_KI270376v1,length=1136>
##contig=<ID=chrUn_KI270374v1,length=2656>
##contig=<ID=chrUn_KI270372v1,length=1650>
##contig=<ID=chrUn_KI270373v1,length=1451>
##contig=<ID=chrUn_KI270375v1,length=2378>
##contig=<ID=chrUn_KI270371v1,length=2805>
##contig=<ID=chrUn_KI270448v1,length=7992>
##contig=<ID=chrUn_KI270521v1,length=7642>
##contig=<ID=chrUn_GL000195v1,length=182896>
##contig=<ID=chrUn_GL000219v1,length=179198>
##contig=<ID=chrUn_GL000220v1,length=161802>
##contig=<ID=chrUn_GL000224v1,length=179693>
##contig=<ID=chrUn_KI270741v1,length=157432>
##contig=<ID=chrUn_GL000226v1,length=15008>
##contig=<ID=chrUn_GL000213v1,length=164239>
##contig=<ID=chrUn_KI270743v1,length=210658>
##contig=<ID=chrUn_KI270744v1,length=168472>
##contig=<ID=chrUn_KI270745v1,length=41891>
##contig=<ID=chrUn_KI270746v1,length=66486>
##contig=<ID=chrUn_KI270747v1,length=198735>
##contig=<ID=chrUn_KI270748v1,length=93321>
##contig=<ID=chrUn_KI270749v1,length=158759>
##contig=<ID=chrUn_KI270750v1,length=148850>
##contig=<ID=chrUn_KI270751v1,length=150742>
##contig=<ID=chrUn_KI270752v1,length=27745>
##contig=<ID=chrUn_KI270753v1,length=62944>
##contig=<ID=chrUn_KI270754v1,length=40191>
##contig=<ID=chrUn_KI270755v1,length=36723>
##contig=<ID=chrUn_KI270756v1,length=79590>
##contig=<ID=chrUn_KI270757v1,length=71251>
##contig=<ID=chrUn_GL000214v1,length=137718>
##contig=<ID=chrUn_KI270742v1,length=186739>
##contig=<ID=chrUn_GL000216v2,length=176608>
##contig=<ID=chrUn_GL000218v1,length=161147>
##contig=<ID=chrEBV,length=171823>
##fileDate=20210513
##priorSomaticIndelRate=1e-06
##priorSomaticSnvRate=0.0001
##reference=file:///gpfs42/robbyfs/scratch/lab_lpasquali/msubirana/ref/GCA_000001405.15_GRCh38_no_alt_analysis_set.fa
##source=strelka
##source_version=2.9.10
##startTime=Thu May 13 15:59:02 2021
##bcftools_viewVersion=1.3.1+htslib-1.3.1
##bcftools_viewCommand=view NET1/results/variants/prove/strelka.merged.annotated.vcf.gz
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	NET1BL	NET1TI
chr1	10109	.	A	T	.	LowEVS	AC=0;AF=0;AN=0;DP=1443;MQ=14.16;MQ0=786;NT=ref;QSS=8;QSS_NT=8;ReadPosRankSum=-0.1;SGT=AA->AT;SNVSB=0;SOMATIC;SomaticEVS=0.49;TQSS=2;TQSS_NT=2;set=FilteredInAll	AD:AU:CU:DP:FDP:GU:SDP:SUBDP:TU	51,0:51,403:0,10:84:33:0,2:8:0:0,14	67,5:67,554:0,15:122:50:0,2:24:0:5,28
chr1	10182	.	A	C	.	LowEVS	AC=0;AF=0;AN=0;DP=1005;MQ=13.89;MQ0=522;NT=ref;QSS=1;QSS_NT=1;ReadPosRankSum=0.07;SGT=AA->AA;SNVSB=0;SOMATIC;SomaticEVS=0.2;TQSS=1;TQSS_NT=1;set=FilteredInAll	AD:AU:CU:DP:FDP:GU:SDP:SUBDP:TU	20,0:20,183:0,18:54:34:0,3:4:0:0,0	34,2:34,328:2,31:79:43:0,4:4:0:0,0
chr1	10248	.	A	T	.	LowEVS	AC=0;AF=0;AN=0;DP=536;MQ=16.97;MQ0=223;NT=ref;QSS=12;QSS_NT=12;ReadPosRankSum=0;SGT=AA->AT;SNVSB=0;SOMATIC;SomaticEVS=0.44;TQSS=1;TQSS_NT=1;set=FilteredInAll	AD:AU:CU:DP:FDP:GU:SDP:SUBDP:TU	15,0:15,146:0,8:40:25:0,1:189:0:0,8	20,3:20,178:0,16:60:37:0,2:287:0:3,27
chr1	10390	.	C	A	.	LowEVS	AC=0;AF=0;AN=0;DP=611;MQ=15.04;MQ0=289;NT=ref;QSS=2;QSS_NT=2;ReadPosRankSum=0;SGT=CC->CC;SNVSB=0;SOMATIC;SomaticEVS=0.21;TQSS=1;TQSS_NT=1;set=FilteredInAll	AD:AU:CU:DP:FDP:GU:SDP:SUBDP:TU	14,0:0,10:14,179:36:22:0,0:144:0:0,1	25,2:2,19:25,254:47:20:0,0:232:0:0,1
chr1	10397	.	C	A	.	LowEVS	AC=0;AF=0;AN=0;DP=939;MQ=14.67;MQ0=481;NT=ref;QSS=6;QSS_NT=6;ReadPosRankSum=1.03;SGT=CC->AC;SNVSB=1.27;SOMATIC;SomaticEVS=0.07;TQSS=2;TQSS_NT=2;set=FilteredInAll	AD:AU:CU:DP:FDP:GU:SDP:SUBDP:TU	23,1:1,17:23,255:53:29:0,3:9:0:0,0	35,2:2,17:35,360:78:40:1,3:23:0:0,1
chr1	10400	.	C	T	.	LowEVS	AC=0;AF=0;AN=0;DP=944;MQ=14.52;MQ0=478;NT=ref;QSS=16;QSS_NT=16;ReadPosRankSum=1.8;SGT=CC->CT;SNVSB=2.15;SOMATIC;SomaticEVS=0.52;TQSS=2;TQSS_NT=2;set=FilteredInAll	AD:AU:CU:DP:FDP:GU:SDP:SUBDP:TU	23,0:0,2:23,277:50:27:0,0:3:0:0,17	32,6:0,1:32,383:79:41:0,1:4:0:6,32
chr1	10401	.	T	A	.	LowEVS	AC=0;AF=0;AN=0;DP=927;MQ=14.49;MQ0=472;NT=ref;QSS=1;QSS_NT=1;ReadPosRankSum=-0.59;SGT=TT->TT;SNVSB=0;SOMATIC;SomaticEVS=0.2;TQSS=1;TQSS_NT=1;set=FilteredInAll	AD:AU:CU:DP:FDP:GU:SDP:SUBDP:TU	23,0:0,19:0,15:49:26:0,2:7:0:23,255	36,2:2,24:0,15:77:39:0,5:11:0:36,369
chr1	10443	.	C	A	.	LowEVS	AC=0;AF=0;AN=0;DP=545;MQ=15.59;MQ0=266;NT=ref;QSS=1;QSS_NT=1;ReadPosRankSum=1.58;SGT=CC->CC;SNVSB=0;SOMATIC;SomaticEVS=0.07;TQSS=1;TQSS_NT=1;set=FilteredInAll	AD:AU:CU:DP:FDP:GU:SDP:SUBDP:TU	23,0:0,1:23,165:31:7:0,1:4:0:1,19	35,1:1,2:35,273:46:9:0,3:1:0:1,23
chr1	10462	.	T	C	.	LowEVS	AC=0;AF=0;AN=0;DP=376;MQ=16.86;MQ0=164;NT=ref;QSS=31;QSS_NT=31;ReadPosRankSum=2.4;SGT=TT->CT;SNVSB=0;SOMATIC;SomaticEVS=0.48;TQSS=1;TQSS_NT=1;set=FilteredInAll	AD:AU:CU:DP:FDP:GU:SDP:SUBDP:TU	16,1:0,1:1,8:24:7:0,1:0:0:16,82	25,4:0,2:4,20:32:3:0,2:1:0:25,122
chr1	10463	.	A	T	.	LowEVS	AC=0;AF=0;AN=0;DP=363;MQ=17.12;MQ0=157;NT=ref;QSS=26;QSS_NT=26;ReadPosRankSum=2.4;SGT=AA->AT;SNVSB=0;SOMATIC;SomaticEVS=0.18;TQSS=1;TQSS_NT=1;set=FilteredInAll	AD:AU:CU:DP:FDP:GU:SDP:SUBDP:TU	16,1:16,75:0,2:24:7:0,1:0:0:1,6	25,4:25,124:0,0:32:3:0,0:0:0:4,17
chr1	14522	.	G	A	.	LowEVS	AC=0;AF=0;AN=0;DP=104;MQ=16.94;MQ0=43;NT=ref;QSS=6;QSS_NT=6;ReadPosRankSum=-1.23;SGT=GG->AG;SNVSB=2.88;SOMATIC;SomaticEVS=0.24;TQSS=2;TQSS_NT=2;set=FilteredInAll	AD:AU:CU:DP:FDP:GU:SDP:SUBDP:TU	19,1:1,1:0,0:20:0:19,37:0:0:0,0	23,4:4,6:0,0:27:0:23,60:0:0:0,0
chr1	14542	.	A	G	.	LowEVS	AC=0;AF=0;AN=0;DP=112;MQ=15.82;MQ0=55;NT=ref;QSS=8;QSS_NT=8;ReadPosRankSum=-0.93;SGT=AA->AG;SNVSB=2.02;SOMATIC;SomaticEVS=0.24;TQSS=2;TQSS_NT=2;set=FilteredInAll	AD:AU:CU:DP:FDP:GU:SDP:SUBDP:TU	19,1:19,41:0,0:20:0:1,1:0:0:0,0	20,4:20,62:0,0:25:1:4,7:0:0:0,0
chr1	14699	.	C	G	.	LowEVS	AC=0;AF=0;AN=0;DP=48;MQ=20.88;MQ0=4;NT=ref;QSS=31;QSS_NT=31;ReadPosRankSum=-1.13;SGT=CC->CG;SNVSB=0;SOMATIC;SomaticEVS=2.77;TQSS=1;TQSS_NT=1;set=FilteredInAll	AD:AU:CU:DP:FDP:GU:SDP:SUBDP:TU	14,0:0,0:14,18:14:0:0,3:0:0:0,0	14,3:0,0:14,23:17:0:3,4:0:0:0,0
chr1	14815	.	C	T	.	LowEVS	AC=0;AF=0;AN=0;DP=121;MQ=15.9;MQ0=64;NT=ref;QSS=22;QSS_NT=22;ReadPosRankSum=2.09;SGT=CC->CT;SNVSB=2.42;SOMATIC;SomaticEVS=0.49;TQSS=2;TQSS_NT=2;set=FilteredInAll	AD:AU:CU:DP:FDP:GU:SDP:SUBDP:TU	17,0:0,0:17,43:17:0:0,0:0:0:0,1	22,3:0,0:22,71:26:1:0,0:0:0:3,6
chr1	15647	.	C	G	.	LowEVS	AC=0;AF=0;AN=0;DP=162;MQ=21.26;MQ0=32;NT=ref;QSS=2;QSS_NT=2;ReadPosRankSum=1.07;SGT=CC->CC;SNVSB=0.78;SOMATIC;SomaticEVS=0.1;TQSS=2;TQSS_NT=2;set=FilteredInAll	AD:AU:CU:DP:FDP:GU:SDP:SUBDP:TU	49,5:0,0:49,73:54:0:5,5:0:0:0,0	51,6:0,0:51,78:58:1:6,6:0:0:0,0
chr1	16288	.	C	G	.	LowEVS	AC=0;AF=0;AN=0;DP=73;MQ=21.65;MQ0=15;NT=ref;QSS=7;QSS_NT=7;ReadPosRankSum=-0.7;SGT=CC->CG;SNVSB=0.46;SOMATIC;SomaticEVS=0.11;TQSS=1;TQSS_NT=1;set=FilteredInAll	AD:AU:CU:DP:FDP:GU:SDP:SUBDP:TU	15,3:0,0:15,25:18:0:3,5:0:0:0,0	25,6:0,0:25,32:31:0:6,11:0:0:0,0
chr1	16809	.	C	G	.	LowEVS	AC=0;AF=0;AN=0;DP=144;MQ=18.56;MQ0=24;NT=ref;QSS=1;QSS_NT=1;ReadPosRankSum=-0.26;SGT=CC->CC;SNVSB=0;SOMATIC;SomaticEVS=0.09;TQSS=2;TQSS_NT=2;set=FilteredInAll	AD:AU:CU:DP:FDP:GU:SDP:SUBDP:TU	35,4:0,0:35,50:39:0:4,7:0:0:0,0	44,4:0,0:44,77:48:0:4,10:0:0:0,0
`

**Comment by p-priestley** [comment]
Closing issue due to age.   If still outstanding, apologies and feel free to open a new issue.
