### ISSUE TITLE
working with haploid organisms

### ISSUE THREAD

**Issue by MikiSchikora** [hartwigmedical/gridss-purple-linx#4]
I wonder whether this tool would be also useful to detect structural variation between strains of haploid unicellular organisms (like Candida glabrata, which is what I am working on). Do you have any recommendation regarding the best parameter combinations to use? My idea would be to run the pipeline loading the .bam files for the reference (as normal) and the strain of interest (as tumor), in order to identify variants in the strain of interest. Does it make any sense?

**Comment by p-priestley** [comment]
This pipeline as a whole is not suitable since PURPLE and LINX currently have fundamental assumptions about the human genome, but running GRIDSS with similar somatic filters to what we have used may be suitable for the task.

**Comment by MikiSchikora** [comment]
Thanks. I assume that this cannot be solved by generating all the optional input files (like repeats, viral sequences, annotations files ...) for the haploid genome right? I assume you refer to assumptions like the stated in the following sentence:

"Some of the unique features in the PURPLE penalty function are additional penalties for solutions with major allele copy number less than 1 (since homozygous loss of large sections of the genome are unlikely)"

**Comment by p-priestley** [comment]
Closing.  This is not something on our radar
