### ISSUE TITLE
Using HG38 BAMs and reference with the correct blacklist

### ISSUE THREAD

**Issue by sbilobram** [hartwigmedical/gridss-purple-linx#40]
Hi All,
  I would like to use the Docker Image **gridss-purple-linx** with my hg38 BAMs.  I would like to use the recommended Blacklist but the workflow seems to only accept the file **ENCFF001TDO.bed**  no matter what I do.    I have downloaded the Blacklist file: **ENCFF356LFX.bed** and understood it to be the one accompanying HG38 BAMs.  
Is this not the case ?  
How can I get the Container Image to use this updated Blcaklist ? 

Here is log for the beginning of a typical run, showing the HG38 ref. using the old blacklist:

_Tue Feb 15 13:14:40 PST 2022: Full log file is: WDverySmallBam/gridss/gridss.full.20220215_131440.gphost12.bcgsc.ca.23067.log
Tue Feb 15 13:14:40 PST 2022: Found /usr/bin/time
Tue Feb 15 13:14:40 PST 2022: Using reference genome **"testRefData/refgenomes/Homo_sapiens.GRCh38/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna"**
Tue Feb 15 13:14:40 PST 2022: Using assembly bam WDverySmallBam/gridss/smallPOG.assembly.bam
Tue Feb 15 13:14:40 PST 2022: Using output VCF WDverySmallBam/gridss/smallPOGT.gridss.driver.vcf.gz
Tue Feb 15 13:14:40 PST 2022: WARNING: GRIDSS scales sub-linearly at high thread count. Up to 8 threads is the recommended level of parallelism.
Tue Feb 15 13:14:40 PST 2022: Using 64 worker threads.
**Tue Feb 15 13:14:40 PST 2022: Using blacklist testRefData/dbs/gridss/ENCFF001TDO.bed**
Tue Feb 15 13:14:40 PST 2022: Using JVM maximum heap size of 32g for assembly and variant calling.
Tue Feb 15 13:14:40 PST 2022: Using input file testData/verySmallNormal.bam
Tue Feb 15 13:14:40 PST 2022: Using input file testData/verySmallTumour.bam_

**Comment by sbilobram** [comment]
Following up and clarifying the error and offering a solution.  Please comment if I post wrong info.  
PROBLEM: Unfortunately when running the convenient shell script gridss-purple-linx.sh, the  GRIDSS module will use the blacklist dbs/gridss/ENCFF001TDO.bed  whether the inputs are hg19 or HG38 BAMS.  See comment above.
SOLUTION: Download the  ENCFF356LFX.bed (for HG38) and use the --blacklist option to get around this error.
 The pipeline script gridss-purple-linx.sh has the parameter switch --gridds_arg
that lets one pass options to GRIDSS.  Run something like : --gridss_args '--blacklist refData/dbs/gridss/ENCFF356LFX.bed'  Make sure to include the quotes or an error will result.
Find the resource files at: https://github.com/hartwigmedical/gridss-purple-linx#reference-data
After downloading the decompressing the HG38 Reference and Resource archive  eg. tar -xvzf gpl_ref_data_38.gz C ./refData,  note that the Blacklist  is still the old hg19 bed :  refData/dbs/gridss/ENCFF001TDO.bed

Both the old (hg19: ENCFF001TDO.bed) and new (HG38: ENCFF356LFX.bed) Blacklists are available here:
https://github.com/PapenfussLab/gridss/blob/master/QuickStart.md
 https://github.com/PapenfussLab/gridss/tree/master/example
.

**Comment by charlesshale** [comment]
Thanks for proposing a solution and finding the relevant file. The correct HG38 file is also available through the HMF Resource page (https://resources.hartwigmedicalfoundation.nl/ -> RepeatMasker -> 38).
