### ISSUE TITLE
reference data package

### ISSUE THREAD

**Issue by tarfy** [hartwigmedical/gridss-purple-linx#42]
Hi,

I have downloaded the reference data file from https://resources.hartwigmedicalfoundation.nl/ -> HMFTools-Resources/GRIDSS-Purple-Linx-Docker/gpl_ref_data_hg38.gz. When I run the gridss-purple-linx pipeline through docker I am getting the error: 

`Missing reference genome /refdata/refgenomes/Homo_sapiens.GRCh38/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna - specify with -r `

The gpl_ref_data_hg38 that I downloaded is a single file. Do I need to add additional reference genome files to my refdata folder and if so, what files are necessary and what should the directory structure be?

Thanks, E.

**Comment by charlesshale** [comment]
The file needs to be unzipped - eg "tar xvf gpl_ref_data_hg38.gz"

I will be releasing an updated set of resource files later this week to work with our latest versions of Linx and Purple.

thanks.
