### ISSUE TITLE
Add option to pass validation stringency to gridss/cobalt/amber

### ISSUE THREAD

**Issue by lkhilton** [hartwigmedical/gridss-purple-linx#6]
I'm working with some old WGS BAM files that don't conform to current SAM specifications. As such, gridss throws the following error: 

```Exception in thread "main" htsjdk.samtools.SAMFormatException: SAM validation error: ERROR: Record 874744391, Read name HS27_17:3:1307:5837:62295, MAPQ should be 0 for unmapped read.```

I see that running gridss in standalone mode includes a --picardoptions option that would allow me to set VALIDATION_STRINGENCY=LENIENT. Is it possible to include this option in both gridss-purple-linx.sh and gridss.sh? 

Thanks for your time.

**Comment by d-cameron** [comment]
`--picardoptions` won't work since cobalt/amber don't use picard tools. Will need to have an explicit validation strigency argument
