### ISSUE TITLE
failed to download reference genome

### ISSUE THREAD

**Issue by pachchek** [hartwigmedical/gridss-purple-linx#9]
Hi. The link to download the reference genome didn't work.
can you provide another link pls.

https://resources.hartwigmedicalfoundation.nl/HMFTools-Resources%2FGRIDSS-Purple-Linx-Docker/gridss-purple-linx-docker-image-refdata-hg19.tar.gz

thank you

**Comment by d-cameron** [comment]
https://nc.hartwigmedicalfoundation.nl/index.php/s/a8lgLsUrZI5gndd/download?path=%2FHMFTools-Resources%2FGRIDSS-Purple-Linx-Docker&files=gridss-purple-linx-hg19-refdata.tar.gz

**Comment by pachchek** [comment]
thank you.
